### ISSUE TITLE
Incorrect return type for InputBag::get with default value

### ISSUE THREAD

**Issue by magikid** [phpstan/phpstan-symfony#196]
# Expected Behavior

When passing an `int` as the `$default` parameter to `InputBag::get($key, $default)`, I expect phpstan to correctly understand the return type as `string|int`.  If the key is found, `get` will return a string.  If the key is not found, it will return an `int`.

# Actual Behavior

phpstan returns this error:
```
Parameter #2 $default of method Symfony\Component\HttpFoundation\InputBag<string>::get() expects string|null, int given.
```

# Steps to reproduce

I believe these are the relevant lines in my `phpstan.neon` file:
```yaml
includes:
    - vendor/phpstan/phpstan-symfony/extension.neon
    - vendor/phpstan/phpstan-symfony/rules.neo

parameters:
    symfony:
        container_xml_path: '%currentWorkingDirectory%/var/cache/dev/App_KernelDevDebugContainer.xml'
```

In my FooController.php class, I have:
```php
    /**
     * @Route("/bar")
     * @Security("is_granted('baz')")
     */
    public function barAction(
        Request $request,
    ): Response {
        $page = $request->query->get('page', 1);
    }
```

vendor/bin/phpstan analyse -c phpstan.neon FooController.php

# Specifications
* phpstan version: 0.12.98
* PHP version: 8.0.8

# Other info
When calling `InputBag::get($key, $default)`, if the key isn't found in the `InputBag` then the `$default` value is returned.  The default value can be of any scalar type (`string|int|float|bool|null`).  The default value isn't cast at all so if you provide an `int`, the function will also return an `int
