### ISSUE TITLE
Load .env file

### ISSUE THREAD

**Issue by VincentLanglet** [phpstan/phpstan-symfony#53]
# Support question

Since I updated my project to Symfony 4/Flex, I had to create `.env`, ... files with some values.
For example I have 
```
DATABASE_URL=mysql://user:password@127.0.0.1:3300/database
```

This file seems to not be loaded by phpstan
```
In EnvVarProcessor.php line 131:
  Environment variable not found: "DATABASE_URL".
```

 with this config (phpstan.neon)
```
includes:
    - symfony/vendor/phpstan/phpstan-doctrine/extension.neon
    - symfony/vendor/phpstan/phpstan-symfony/extension.neon
    - symfony/vendor/phpstan/phpstan-phpunit/extension.neon
    - symfony/vendor/phpstan/phpstan-phpunit/rules.neon

parameters:
    autoload_directories:
        - symfony/src/Migrations
    doctrine:
        objectManagerLoader: phpstanLoader.php
    symfony:
        container_xml_path: symfony/var/cache/dev/appAppKernelDevDebugContainer.xml

services:
    -
        class: PhpStan\ProxyQueryMethodsClassReflectionExtension
        tags: [phpstan.broker.methodsClassReflectionExtension]
```

phpstanLoader.php
```
<?php

use AssuranceVie\Kernel;

require __DIR__.'/symfony/vendor/autoload.php';

$kernel = new Kernel('test', true);
$kernel->boot();

return $kernel->getContainer()->get('doctrine')->getManager();
```

What should I add ? I didn't find it in the documentation.
