### ISSUE TITLE
Undefined variable $container in config files

### ISSUE THREAD

**Issue by alexander-schranz** [phpstan/phpstan-symfony#55]
If you have for example a `config/packages/framework.php` 

Phpstan will report `Undefined variable $container` if possible this should always be defined in $container and be typed as ContainerBuilder.

Workaround:

```yaml
# phpstan.neon

parameters:
    # ...

    ignoreErrors:
        - message: '#Undefined variable: \$container#'
          path: '%currentWorkingDirectory%/config/packages/*'
```
